---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/applications":
    get:
      summary: List all applications
      tags:
      - Applications
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        token:
                          type: string
                          example: some_token
                        name:
                          type: string
                          example: My Application
                        chats_count:
                          type: integer
                          example: 0
                      required:
                      - token
                      - name
                      - chats_count
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
    post:
      summary: Create an application
      tags:
      - Applications
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: some_token
                      name:
                        type: string
                        example: My Application
                      chats_count:
                        type: integer
                        example: 0
                    required:
                    - token
                    - name
                    - chats_count
                  status:
                    type: integer
                    example: 201
                required:
                - success
                - data
                - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/applications/{token}":
    parameters:
    - name: token
      in: path
      description: Application token
      required: true
      schema:
        type: string
    get:
      summary: Show application details
      tags:
      - Applications
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: some_token
                      name:
                        type: string
                        example: My Application
                      chats_count:
                        type: integer
                        example: 0
                    required:
                    - token
                    - name
                    - chats_count
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
    patch:
      summary: Update an application
      tags:
      - Applications
      parameters: []
      responses:
        '200':
          description: updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: some_token
                      name:
                        type: string
                        example: My Application
                      chats_count:
                        type: integer
                        example: 0
                    required:
                    - token
                    - name
                    - chats_count
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/applications/{application_token}/chats":
    parameters:
    - name: application_token
      in: path
      description: Application token
      required: true
      schema:
        type: string
    get:
      summary: List all chats for an application
      tags:
      - Chats
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        number:
                          type: integer
                          example: 1
                        messages_count:
                          type: integer
                          example: 0
                      required:
                      - number
                      - messages_count
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
    post:
      summary: Create a chat under an application
      tags:
      - Chats
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      number:
                        type: integer
                        example: 1
                      messages_count:
                        type: integer
                        example: 0
                    required:
                    - number
                    - messages_count
                  status:
                    type: integer
                    example: 201
                required:
                - success
                - data
                - status
  "/applications/{application_token}/chats/{number}":
    parameters:
    - name: application_token
      in: path
      required: true
      schema:
        type: string
    - name: number
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show a chat by number
      tags:
      - Chats
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      number:
                        type: integer
                        example: 1
                      messages_count:
                        type: integer
                        example: 0
                    required:
                    - number
                    - messages_count
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
  "/applications/{application_token}/chats/{chat_number}/messages":
    parameters:
    - name: application_token
      in: path
      required: true
      schema:
        type: string
    get:
      summary: List all messages in a chat
      tags:
      - Messages
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        number:
                          type: integer
                          example: 1
                        body:
                          type: string
                          example: Hello World
                      required:
                      - number
                      - body
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
    post:
      summary: Create a new message
      tags:
      - Messages
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      number:
                        type: integer
                        example: 1
                      body:
                        type: string
                        example: Hello World
                    required:
                    - number
                    - body
                  status:
                    type: integer
                    example: 201
                required:
                - success
                - data
                - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
  "/applications/{application_token}/chats/{chat_number}/messages/{id}":
    parameters:
    - name: application_token
      in: path
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      required: true
      schema:
        type: integer
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show message details
      tags:
      - Messages
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: object
                    properties:
                      number:
                        type: integer
                        example: 1
                      body:
                        type: string
                        example: Hello World
                    required:
                    - number
                    - body
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
  "/applications/{application_token}/chats/{chat_number}/messages/search":
    parameters:
    - name: application_token
      in: path
      required: true
      schema:
        type: string
    - name: chat_number
      in: path
      required: true
      schema:
        type: integer
    - name: q
      in: query
      description: Search query
      schema:
        type: string
    get:
      summary: Search messages in chat
      tags:
      - Messages
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    nullable: true
                    example:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        number:
                          type: integer
                          example: 1
                        body:
                          type: string
                          example: Hello World
                      required:
                      - number
                      - body
                  status:
                    type: integer
                    example: 200
                required:
                - success
                - data
                - status
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
