:concurrency: 5
:queues:
  - default

:schedule:
  sync_redis_counters:
    cron: "* * * * *"
    class: SyncRedisCountersJob
    queue: default
    description: "Syncs Redis chat counters with the database"
